### ISSUE TITLE
BV pipeline is green even when the proxy fails to bootstrap

### ISSUE THREAD

**Issue by NamelessOne91** [SUSE/susemanager-ci#1108]
The issue has been noticed on the 4.3.11 BV NUE pipeline.

Running a build with these option flagged

- enable_proxy_stages
- must_boot_node

Should produce a failure at the pipeline level in case one of the proxy stages fails.

Right now it does not and the pipeline is shown as "green".

Take [Build 167](https://ci.suse.de/view/Manager/view/Manager-4.3/job/manager-4.3-qe-build-validation-NUE/167/) for reference

**Comment by NamelessOne91** [comment]
Docs for the sh global function state this about using **returnStatus**

> Normally, a script which exits with a nonzero status code will cause the step to fail with an exception. If this option is checked, the return value of the step will instead be the status code. You may then compare it to zero, for example

Currently most of the steps for the proxy save the `returnStatus` to a variable but don't use it to determine whether a failure occurred or not. The same holds true for the monitoring server.
Only the MUs stages will properly fail if a script execution does not return with 0.

**Comment by nodeg** [comment]
I can confirm this issue. I saw the same with the monitoring stages.


![Image](https://github.com/SUSE/susemanager-ci/assets/12104291/d782f012-fc46-45b9-ba55-81297c764275)

![Image](https://github.com/SUSE/susemanager-ci/assets/12104291/503390a0-d534-4b7a-b4a0-61040d893396)

![Image](https://github.com/SUSE/susemanager-ci/assets/12104291/782a03d4-a577-4a0d-a3b2-8d4b541912bd)

**Comment by NamelessOne91** [comment]
Discussed approaches

1) Fail fast: if a test fails, the pipeline fails.

This mimics whats a lot of us do when they are actually working on BV, as they would likely stop and debug the first failure that occurs. It saves time and avoids having misleading "greens" being shown in the UI and reports.

2) Fail only in critical stages

The pipeline should fail only when a stage that is crucial for the following ones fails. In other cases the pipeline keeps on running and the errors are stored to be reported at the end.
This introduces a degree of complexity but allows to leave the pipeline running extensive parts of the testsuite and check the results later on (example: runs over the weekend).

3) Fine grained control over failures

Use a variable to conditionally decide whether to fail fast or not. 
More complexity VS More control  kind of situation.

**Comment by nodeg** [comment]
I just saw, that this issue was opened in `susemanager-ci`. If you create an issue, please always open it in `spacewalk`, so we have all our labels, etc. available.
